### PR TITLE
Add Sprig template functions

### PR DESCRIPTION
**Pull request by micbar**
## Description

Add the Sprig Template functions to Calens Changelog Generator.

It gives us a set of Generic functions listed here https://github.com/Masterminds/sprig/blob/master/functions.go#L93

## Motivation
- We need to do arithmetic operations in our changelog template if we create GitHub compare links
- This would add a basic set of semver functions

### CODE REVIEW

**Comment by micbar** [comment]
Tests are passing:
```
go test -v
=== RUN   TestReadFile
=== RUN   TestReadFile/#00
=== RUN   TestReadFile/#01
=== RUN   TestReadFile/#02
--- PASS: TestReadFile (0.00s)
    --- PASS: TestReadFile/#00 (0.00s)
    --- PASS: TestReadFile/#01 (0.00s)
    --- PASS: TestReadFile/#02 (0.00s)
PASS
ok      github.com/restic/calens        0.014s
```

**Review by tboerger — APPROVED** [review]
Great, more flexibility for our owncloud changelogs ❤️

**Review by fd0 — APPROVED** [review]
LGTM, thanks!

**Comment by fd0** [comment]
I've merged this as https://github.com/restic/calens/commit/fb4f84a4e5a7cc3f9818423b6652df7f7c677f5e

**Comment by micbar** [comment]
@fd0 Cool! Thanks.
We will be able to create github version compare links now.

**Comment by fd0** [comment]
You're welcome. Happy owncloud user here :)

**Pull request closed without merging**
